server:
  port: 9090
  servlet:
    context-path: /yingx
    #jsp热部署
    jsp:
      init-parameters:
        development: true

#将数据源相关的参数告诉springboot
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingxue
    username: root
    password: root


  #添加视图解析器
  mvc:
    view:
      prefix: /
      suffix: .jsp
      #入参全局配置日期格式
    date-format: yyyy-MM-dd
    #统一编码格式
  http:
    encoding:
      charset: UTF-8
      force: true
  #出参格式设置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    database: 0
    port: 7000
    host: 192.168.52.12

  #spring.redis.port=7000
  #    spring.redis.database=0
  #    spring.redis.host=192.168.52.12
  data:
    elasticsearch:
      cluster-nodes: 192.168.52.13:9300

#将mybatis相关信息告诉springboot

mybatis:
  mapper-locations: classpath:com/fd/mapper/*.xml
  type-aliases-package: com.fd.entity

